### ISSUE TITLE
Running / exporting no longer works

### ISSUE THREAD

**Issue by ltratt** [softdevteam/eco#181]
Running a PyHyp program no longer works. If I press "run", I get this exception:
```python
Traceback (most recent call last):
  File "eco.py", line 1611, in run
    p = self.window.getEditor().export(run=True, source=str(ed.filename))
  File "/home/ltratt/src/eco/lib/eco/nodeeditor.py", line 1060, in export
    return self.tm.export(None, run, profile, source=source, debug=debug)
  File "/home/ltratt/src/eco/lib/eco/treemanager.py", line 1667, in export
    for p, _, _, _ in self.parsers:
ValueError: too many values to unpack
```

**Comment by ptersilie** [comment]
Fixed in #183
